name: Matrix Demo 
on: push
jobs:
  build:
    continue-on-error: true # we can continue even if some combinations faul
    strategy:
      matrix:
        node-version: [12, 14, 16, 18, 20]
        operating-system: [ubuntu-latest, windows-latest]
    runs-on: $ {{ matrix.operating-system }} # run in parallel for all os
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: $ {{ matrix.node-version }} # use diffrent versions in combinaitons
      - name: Install Dependencies 
        run: npm ci
      - name: Build project
        run: npm run build