name: Reusable Deploy
on: 
  workflow_call
    inputs:
      artifact-name: 
        description: The name of the  deployable artifact files.
        required: false # whether is required or not, if not we can use default
        default: dist # if a value is not provided we'll use this
        type: string # type of the value
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/download-artifact@v3
        with:
          name: $ {{ inputs.artifact-name }}
      - name: List files
        run: ls 
      - name: Output information
        run: echo "Deploying & uploading ..."